### PR TITLE
Python plotting mods/enhancements (feature/python plotting)

### PR DESCRIPTION
**Pull request by michelleharrold**
This PR addresses several Python plotting-related issues and enhancements. Changes have been made to [speed up the plotting](https://github.com/NCAR/container-dtc-nwp/issues/40), address [issue](https://github.com/NCAR/container-dtc-nwp/issues/41) with contouring, and issues with unphysical 500 hPa absolute vorticity values around domain border.

To speed up the plotting, a single Python script (ALL_plot_allvars.py) is now used to plot the 10 variables of interest. Transitioning from 10 individual scripts reduced I/O time. An option to run the individual scripts is still in the run_python.ksh script, but it is commented out.

To address the contouring issues and the unphysical border in the 500 hPa absolute vorticity plots, changes were made to the ALL_plot_allvars.py script as well as plot_slp.py and plot_500mbH_W_Vort.py. Logic was added to these scripts to not plot contour lines if the range of the SLP and 500 hPa heights was smaller then a specified range. In addition, for 500 hPa absolute vorticity, the Gaussian smoothing was reduced (to 0.5) to alleviate the border of unphysical values around the domain edge.

A small change was also made for plotting 2-5 km max UH to modify the colorbar min/max values.

Finally, while not related to Python plotting, in testing, an [issue](https://github.com/NCAR/container-dtc-nwp/issues/44) was discovered with running GSI with the snow case. This issue is addressed by adding the PREPBUFR environment variable under the ‘GSI settings’ to the set_env.ksh file under scripts/snow_20160123.

Testing done:
Ran sandy, snow, and derecho cases with the ALL_plot_allvars.py script and the individual plotting scripts to ensure the same behavior/output and to ensure new mods/changes were implemented as intended. Visually inspected plots to make sure contouring issues and issues with 500 hPa absolute vorticity have been addressed. Testing was done with v3.4 tag of code components on a Mac.

### CODE REVIEW

**Review by jwolff-ncar — APPROVED** [review]
I have looked at the changes visually and run Sandy and all looks good to me! If you prefer I test a different case I can definitely do that. I was just trying to be fast and I have limited space on my current machine (should get my new one on Thrs when I am in the office!). I approve but I am willing to do more testing if you would like me to.

I am curious, is it easy to remove the 0-1 axis and outer box around the image? I hadn't noticed it before but it jumped out at me this time. Not a big deal.

**Comment by fossell** [comment]
I will test this feature branch and see if I encounter the same border issues as Jamie. In old python plots I tested from Workshop this spring do not have the strange border.

**Comment by michelleharrold** [comment]
As a note, I tried running with the 'trim' command commented out, and while it allowed for whitespace around the plot, I didn't get the strange border. I am perplexed!

**Comment by fossell** [comment]
Just a quick update, I am still not able to test this due to continuing build issues.

**Comment by michelleharrold** [comment]
@fossell -- I didn't make any changes to the Dockerfiles for this PR, and I tested with pulling the v3.4 images from DockerHub. Would that be an option for testing?

**Comment by fossell** [comment]
@michelleharrold - Doh! Yes, yes I can. I've been so entrenched in the build failures lately forgot about existing images!

Tested the updated python scripts with 3.4 tagged images from Dockerhub and everything was successful. No indication of the weird border lines that Jamie had. Example of SLP plot: 

image

**Review by fossell — APPROVED** [review]

**Pull request merged**
