### PR TITLE
Load MET output from multiple cases into METviewer: feature/issue_78_metv

### PR DESCRIPTION
**Pull request by michelleharrold**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
This was tested on a MacOS and AWS (using the dtcnwp_basic_image_test AMI as a starting point). It was tested in several permutations: 1) ran sandy end-to-end and loaded into a single database, 2) ran a new customized case (sandy2) end-to-end and loaded into a single database, and 3) used sandy and sandy2 MET output to test new functionality of loading into a single METviewer database and into two separate METviewer databases.

- [ ] Recommend testing for the reviewer(s) to perform:</br>
@JohnHalleyGotway - can you please test the new functionality for loading MET output from multiple cases into METviewer? I have tested the functionality, but a second set of eyes would be preferred. I have instructions on the commands [here](https://dtcenter.org/nwp-containers-online-tutorial/hurricane-sandy-case-27-oct-2012/visualize-verification-results); it is a draft, so let me know if you can't see them. The commands work, but I am still working out some of the language and plan on adding a figure to show having multiple cases in a single plot (as well as associated METviewer XML). Also, the example METviewer instructions assume the MET output has already been created.

- [ ] Are any changes to the online tutorial required for this PR?</br>
These changes were done in conjunction with updating the METviewer customization section on the online tutorial. Customization instructions for loading MET output from multiple cases into METviewer are in draft form and will be published once the PR is approved. 

- [ ] Will this PR change the output of any of the existing cases? **No**</br>

- [ ] Please complete this pull request review by **18 Feb. 2022**.</br>

## Pull Request Checklist ##
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow:
Select: **Reviewer(s)**, **Projects(s)**, and **Milestone**.
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes, as permissions allow.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@michelleharrold I do not see any draft website content at that link:
https://dtcenter.org/nwp-containers-online-tutorial/hurricane-sandy-case-27-oct-2012/visualize-verification-results

Here's a screenshot of the revisions I see listed for that page. I assume I should be reviewing content that's newer than 1/5/22. 

Screen Shot 2022-03-06 at 10 59 46 AM

How do you want to make the website changes available for me to review?

**Comment by JohnHalleyGotway** [comment]
I'll use this comment to keep a running list of issues/questions.

- [ ] 3/6/2022: This is not really related to this PR... All of the 'docker pull' commands in the tutorial are preceeded by a 'cd ${PROJ_DIR}' command. I don't think that's needed and it should probably be removed to avoid implying that it does. See all the pages following [Software Containers](https://dtcenter.org/nwp-containers-online-tutorial/software-containers) and look in the "Pull the image from Docker Hub" accordion entry.

**Comment by michelleharrold** [comment]
@JohnHalleyGotway - weird, sorry about the incorrect link to the draft page. Try [this](https://dtcenter.org/node/1886/edit) page instead.

**Review by jwolff-ncar — APPROVED** [review]
I was able to run through this example and get it to work. @JohnHalleyGotway - feel free to test on your side too!

**Pull request merged**
