### PR TITLE
Feature/issue_27_python - Python capability to plot WRF domain

### PR DESCRIPTION
**Pull request by michelleharrold**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tests have been done using the 3 namelist.wps from the sandy, snow, and derecho cases. Successful tests have also been performed on other namelist.wps files using Lambert Conformal projections and Lat-Lon projections (I created some random test namelists for testing purposes). 'Success' is defined as creating an image with the new Python capability that matches the NCL capability for plotting the WRF domain from the namelist.wps file. 

Tests have also been done with using Mercator and Polar Steroegraphic projections. These projection tests provide close but not reproducible results when running with the new Python capability as compared to the NCL capability. Work will be ongoing to fully support Mercator and Polar Steroegraphic projections. As such, these projections are deemed not fully supported.

To run, example command:
```
docker run --rm -it -e LOCAL_USER_ID=`id -u $USER` \
-v ${PROJ_DIR}/container-dtc-nwp/components/scripts/common:/home/scripts/common \
-v ${PROJ_DIR}/container-dtc-nwp/components/scripts/sandy_20121027:/home/scripts/case \
-v ${PROJ_DIR}/data/shapefiles:/home/data/shapefiles -v ${CASE_DIR}/pythonprd:/home/pythonprd \
--name run-sandy-python dtcenter/python:3.5.1 /home/scripts/common/run_python_domain.ksh
```

The run command assumes PROJ_DIR and CASE_DIR have been set. Additionally, it also assumes you have created the ${CASE_DIR}/pythonprd directory. Output is written to ${CASE_DIR}/pythonprd.

Note: This PR also removes NCL-related materials from the repo, per Issue #62. A quick test was run (sandy) to make sure removing NCL-related materials did not cause any issues; everything worked as expected.

- [x] Recommend testing for the reviewer(s) to perform:</br>
@jwolff-ncar -- Please test the three supplied cases (sandy, snow, and derecho) to make sure run commands execute appropriately. If time allows, it would also be great to run a non-supplied namelist.wps through the Python capability, but that will require a bit more work (will need to 1: create a new namelist.wps, and 2: also run the NCL script to confirm the Python capability creates the same plot specs as NCL.)

- [ ] Are any changes to the online tutorial required for this PR? **[Maybe]**</br>
We currently do not provide an example of how to create a plot of a proposed domain on the website. We could add this example under the customization section.

- [ ] Will this PR change the output of any of the existing cases? **[No]**</br>

- [ ] Please complete this pull request review by **15 March 2022**.</br>

## Pull Request Checklist ##
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow:
Select: **Reviewer(s)**, **Projects(s)**, and **Milestone**.
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes, as permissions allow.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jwolff-ncar — APPROVED** [review]
I ran the Sandy and Derecho case and it worked great. I am comfortable merging based on my testing and the extensive testing you did (with other projections). But if others disagree I can run another test.

I will add that adding instructions to the tutorial steps would be great so people can actually use this functionality! We can discuss the best place to put that if you want.

**Comment by michelleharrold** [comment]
@jwolff-ncar - thanks for reviewing. For adding instructions to the website, would [this be a good spot](https://dtcenter.org/nwp-containers-online-tutorial/customization/nwp-components/modify-model-domain)? ALternative suggestion, would be [here](https://dtcenter.org/nwp-containers-online-tutorial/customization/setting-new-experiment/creating-scripts-namelists).

**Comment by jwolff-ncar** [comment]
Either of those would work. Maybe I like the first option better. Another option - what do you think about adding it prior to running WPS on the case pages?

**Comment by michelleharrold** [comment]
We could add it before WPS on the case pages; that would work well. Would we list this as an optional step?

**Comment by jwolff-ncar** [comment]
Yeah, I think that could work. Just mention it is an optional step to look at the domain if they so choose.

**Comment by michelleharrold** [comment]
Sounds good! I will add that to the website and then merge and close this issue.

**Pull request merged**
