### PR TITLE
Feature/issue 33 python_fhr

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
Running the python step for the derecho case no longer results in Traceback error messages like this:
```
Traceback (most recent call last):
  File "/home/scripts/common/python/ALL_plot_allvars.py", line 255, in <module>
    data1 = pygrib.open(EXPT_BASEDIR+'/wrfprs_'+dom+'.'+fhour)
  File "pygrib/_pygrib.pyx", line 321, in pygrib._pygrib.open.__cinit__
OSError: [Errno could not open %s] /home/postprd/wrfprs_d02.00
```
The 2 changes are:
1. Update run_python.ksh to compute the wrfprs filename to be plotted. If it doesn't exist, do not call any python scripts.
2. Change the command line args for ALL_ploy_allvars.py to specify the GRIB file to be plotted instead of re-computing it a second time.

Please refer to the log files attached to the ncar/container-dtc-nwp#33 issue when reviewing this PR.

### CODE REVIEW

**Review by jwolff-ncar — COMMENTED** [review]
Looks reasonable on visual inspection. Will wait for @michelleharrold to test and make sure it runs as expected. Thanks for streamlining this and making the change, @JohnHalleyGotway.

**Comment by michelleharrold** [comment]
@JohnHalleyGotway - I was able to use shapefiles I already had downloaded. I tested the changes for the derecho and sandy cases. Functionality worked as expected, and the Traceback error is no more!

It looks like changes to the python script were implemented in ALL_plot_allvars.py but not the plot_*.py scripts. We technically still support those, so it would be good to migrate the necessary mods into the individual plotting scripts as well. If you want help with that, just let me know.

**Review by michelleharrold — CHANGES_REQUESTED** [review]
@JohnHalleyGotway -- your changes worked with the /scripts/common/python/ALL_plot_allvars.py script. Can you make the same changes in the /scripts/common/python/plot*.py scripts as well?

**Comment by JohnHalleyGotway** [comment]
Thanks for finding that issue @michelleharrold. I updated those other python scripts, made a temporary/local change to run_python.ksh to calls those scripts instead of the ALL_plot_allvars.py script, and tested with Derecho using the command listed on this page:
https://dtcenter.org/nwp-containers-online-tutorial/derecho-case-29-jun-2012/create-graphics
```
docker run --rm -it -e LOCAL_USER_ID=`id -u $USER` \
-v ${PROJ_DIR}/container-dtc-nwp/components/scripts/common:/home/scripts/common \
-v ${PROJ_DIR}/container-dtc-nwp/components/scripts/derecho_20120629:/home/scripts/case \
-v ${CASE_DIR}/postprd:/home/postprd -v ${CASE_DIR}/pythonprd:/home/pythonprd \
--name run-derecho-python dtcenter/python:3.4 /home/scripts/common/run_python.ksh
```
Those tests are still running but I haven't run into any problems. Please proceed with your testing.
Thanks!

**Review by michelleharrold — APPROVED** [review]
@JohnHalleyGotway - I ran sandy and derecho with the individual *py scripts and the ALL*py script. Everything works and runs as expected. I approve!

As a note, we have been getting the 'pcolormesh' warnings since we started using these python scripts -- probably something to look into eventually, but I agree that is out of the purview of this PR.

**Pull request merged**
