### PR TITLE
Remove unused scripts

### LINKED ISSUE #42: Clean up old run files, dockerfiles, etc. from repo for things that are now legacy and not used. (e.g. wps_wrf/run* scripts

### PR DESCRIPTION
**Pull request by fossell**
- Removed dummy run scripts used in previous versions of the system and deleted lines in Dockerfile to copy scripts into container
- Removed extraneous scripts inherited from original ncar docker setup
- Fixes #42 

Note: Opted to keep Dockerfiles for creating data volumes. While we've moved towards direct mount of data instead of data volumes, we still host some (e.g. WPS GEOG) on DockerHub. Should we update that data, we might want to consider updating the DockerHub image, in which case we need to Dockerfile.  Open to discussion on this though.... for example it's unlikely we're ever use the scripts as a data volume again, so perhaps that Dockerfile can be deleted?  
Thoughts? @jwolff-ncar @michelleharrold @mkavulich @JohnHalleyGotway ?

@JohnHalleyGotway - This is ready for testing.

### CODE REVIEW

**Comment by fossell** [comment]
Team decided to remove the data directories (wps_data, gsi_data, case_data, etc.) and corresponding Dockerfiles for data containers.

**Comment by fossell** [comment]
@JohnHalleyGotway - Can you please test this? Or let us know if you're busy and we need someone else to do it.  I am still not able to get a stable working version of the WRF docker container on my computer.

**Comment by JohnHalleyGotway** [comment]
@fossell sorry, I didn't realize that this was on my plate. I'll test today and submit a PR review.

**Review by JohnHalleyGotway — COMMENTED** [review]
I am not able to Docker build wrf. Listed below are the details:

- Reviewed the 22 deleted/modified files and understand the changes.
- Checked out the feature branch locally:
```
mkdir -p feature_47; cd feature_47
git clone https://github.com/NCAR/container-dtc-nwp
git checkout clean_up
```
- Ran through the tutorial exercises on my laptop (sandy-only), following the instructions for running locally, and building images from scratch:
https://dtcenter.org/nwp-containers-online-tutorial/introduction
```
export PROJ_DIR=/Volumes/d1/projects/Containers/pull_requests/feature_47
cd ${PROJ_DIR}/container-dtc-nwp
mkdir data/
cd data/
# Consider switching from wget/tar to more concise curl commands
curl -SL https://dtcenter.ucar.edu/dfiles/container_nwp_tutorial/tar_files/container-dtc-nwp-sandydata_20121027.tar.gz | tar zxC .
curl -SL https://dtcenter.ucar.edu/dfiles/container_nwp_tutorial/tar_files/CRTM_v2.3.0.tar.gz | tar zxC .
curl -SL https://dtcenter.ucar.edu/dfiles/container_nwp_tutorial/tar_files/wps_geog.tar.gz | tar zxC .

# Build WRF
cd wps_wrf ; docker build -t dtcenter/wps_wrf:3.4 . ; cd ..

# Errors out with
Step 11/16 : RUN ls /comsoftware/wrf/WRF-${WRF_VERSION}/main/real.exe /comsoftware/wrf/WRF-${WRF_VERSION}/main/wrf.exe
 ---> Running in 5b7a63745968
ls: cannot access /comsoftware/wrf/WRF-4.1.3/main/real.exe: No such file or directory
ls: cannot access /comsoftware/wrf/WRF-4.1.3/main/wrf.exe: No such file or directory
The command '/bin/sh -c ls /comsoftware/wrf/WRF-${WRF_VERSION}/main/real.exe /comsoftware/wrf/WRF-${WRF_VERSION}/main/wrf.exe' returned a non-zero code: 2
```
Questions:
- On https://dtcenter.org/nwp-containers-online-tutorial/downloading-input-data, should we switch from wget/tar commands to curl one-liners?

**Comment by fossell** [comment]
@JohnHalleyGotway - You are encountering the exact issues that I have as well.  Can you please try to do a fresh clone/build of the main branch (top of repo) and see if you can build the components from top of the repo without worry about this feature?

**Comment by JohnHalleyGotway** [comment]
The build of the main branch works fine!
```
git checkout main
cd wps_wrf ; docker build -t dtcenter/wps_wrf:3.4 . ; cd ..
Successfully built d57d76fb4435
Successfully tagged dtcenter/wps_wrf:3.4
```
FYI, my specs are:
MacOS Catalina, Docker Desktop version 3.5.1, Engine: 20.10.7

**Comment by fossell** [comment]
Well @JohnHalleyGotway's recent failed attempts of main branch at least makes me feel less crazy.  I still have no solutions and can't find a common denominator.

**Comment by fossell** [comment]
I also tested --no-cache option, both with and without DOCKER BUILD env variables. Both failed.  Before each attempt I did a docker system prune --all

**Review by mkavulich — APPROVED** [review]
Changes look good per previous discussion. I was able to build the (almost) full end-to-end workflow twice from scratch using the new Dockerfile changes. There is a known METviewer issue (#45) preventing that from building but that is unrelated to this PR.

**Comment by mkavulich** [comment]
Also ran a Sandy case through the graphics step to ensure the built WRF/UPP containers were functioning as expected

**Pull request merged**
