### PR TITLE
Update Derecho d02 domain

### LINKED ISSUE #25: Address d02 in derecho case

### PR DESCRIPTION
**Pull request by fossell**
This PR fixes #25 .

Changes include:
- Update the nested domain for the Derecho case to be larger and moved over an area of convective interest. 
- Only run Derecho nested domain for subset of forecast hours (fhr15-fhr21)
- Modify run_upp script so that it can process a subset of forecast hours for subdomains. 
- Modify set_env script for each case to define date/time variables for UPP with a "_d01" (or relevant domain tag) so that new run_upp script runs appropriately. 

Tests Performed:

Tested on AWS with CMU AMI for Derecho and Sandy case. New domain for Derecho visually inspected and approved. Domain 2 forecast hour subsets produced without issue.  Sandy ran successfully so no mods here broke other cases.

### CODE REVIEW

**Comment by jwolff-ncar** [comment]
I am sorry I have not had time to run a test on this. I looked through the changes and visually they seem fine but if @mkavulich has time to do a test prior to approval that would be fantastic!

**Review by michelleharrold — APPROVED** [review]
I ran through Sandy on Mac laptop end-to-end (including DA and vx steps). Everything worked as expected, and the output looks good! I do want to mention that the Python plots were all generated as expected, but we do get errors in the output due to the scripts expecting d01 and d02 outputs for every time. We pared down our d02 output times, but don't have logic for that in the Python scripts. Here is the error, e.g.:
OSError: [Errno could not open %s] /home/postprd/wrfprs_d02.03

Since the error doesn't cause the script to crash, we can probably address this later.

**Comment by fossell** [comment]
Thanks @michelleharrold! Will merge now with this confirmation.

**Comment by jwolff-ncar** [comment]
I hadn't tested the python scripts yet and figured there would be some type of error but I am glad it does continue on (I was hoping that would be the case!). We should try and address this at some point.

**Pull request merged**
