### PR TITLE
Feature 93 aws port

### PR DESCRIPTION
**Pull request by TatianaBurek**
Docker file did not get built because of epel-release error. This commit should fix it

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform:</br>
For multiple reviewers, list specific instructions for each:</br>

- [ ] Are any changes to the online tutorial required for this PR? **[Yes or No]**</br>
If **yes**, please describe:</br>

- [ ] Will this PR change the output of any of the existing cases? **[Yes or No]**</br>
If **yes**, please describe:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow:
Select: **Reviewer(s)**, **Projects(s)**, and **Milestone**.
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes, as permissions allow.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by fossell** [comment]
@TatianaBurek - What Dockerfile didn't build? I was testing this morning building from scratch from the main branch (which has previous mods merged already) and everything seemed to work fine.  Though I did have to change the metviewer version in docker-compose.yml.  Can you provide some more details?

**Comment by fossell** [comment]
@TatianaBurek - We can't view the log file from Dockerhub unfortunately, probably because we're not admins and don't have permissions.  So I'm not sure what is going on with the error.  Is there a reason that Dockerhub produced a failure but the Github actions test seems to be ok and I was able to build from scratch on my Mac and AWS and run cases successfully?

**Comment by TatianaBurek** [comment]
Here is the error from the DockerHub:
```
error: failed to solve: executor failed running [/bin/sh -c yum -y update && yum -y install epel-release && yum -y install 'dnf-command(config-manager)' && yum-config-manager --enable PowerTools]: exit code: 1
Build failed using Buildkit
```
I remember fixing it in Dockerfile_for_Singularity  by enabling  PowerTools before installing epel-release but I forgot to make the same change in Dockerfile.

**Comment by fossell** [comment]
@TatianaBurek - Thanks for the info! I'm testing this now. Not sure why I didn't get errors before, but we need the Dockerhub built properly so we'll need this fix regardless. If everything completes successfully I'll go ahead and merge this to main and then wait to see if  our main Dockerhub builds are successful.

**Review by fossell — APPROVED** [review]
I rebuilt the image on both my Mac and AWS and was able to launch the GUI and create a plot for the Sandy case.

**Pull request merged**
